### ISSUE TITLE
why did not add random flip augmentation in this？

### ISSUE THREAD

**Issue by Johnson-yue** [mit-han-lab/data-efficient-gans#10]
Hi，I want to add “Random flip augmentation”  but I am not sure whether is good or not
And I am not sure how to implement it

Did you try “Random flip augmentation” ??? I think this is easiest augment for implementing

**Comment by zsyzzsoft** [comment]
We apply random flip augmentation to all models including baselines. It is used as "augment reals only" but not a part of DiffAugment.

**Comment by junyanz** [comment]
We applied it to the data directly for all the methods, as flipping doesn't change the data distribution for most of the datasets.

**Comment by Johnson-yue** [comment]
Maybe my description is not accurate enough。

I don't want horizontal flipping or vertical flipping in my generated results, because this will change the semantic information of the data, so I won't add it to the real data Horizontal flip or vertical flip data enhancement, because if I add, the generated image will have the effect of horizontal / vertical flipping, which will generate a wrong semantic information.

Because Diffaug doesn't change the distribution of the original data, because I'm wondering if I can add **random flipping** to diffaug, so that the generated results will not have flipped results

**Comment by junyanz** [comment]
@zsyzzsoft could we add it?

**Comment by zsyzzsoft** [comment]
This is not officialy supported, but you may try the code below, which implements a 50% horizontal flip. However, it will NOT meet your purpose, because the original images and the flipped images are indistinguishable to the discriminator after a 50% horizontal flip. Theoretically, any probably other than 50% may work.

For PyTorch,
```
return torch.where(torch.rand(x.size(0), 1, 1, 1, device=x.device) < 0.5, x.flip(3), x)
```
For TensorFlow,
```
return tf.where_v2(tf.random.uniform([tf.shape(x)[0], 1, 1, 1]) < 0.5, x, tf.reverse(x, axis=[3]))
```

**Comment by Johnson-yue** [comment]
Thank you, I will try it
