### ISSUE TITLE
Does this work with Pix2Pix?

### ISSUE THREAD

**Issue by Jaberish** [mit-han-lab/data-efficient-gans#13]
Does this work with Pix2Pix? I was trying to use it for that but the discriminator was way better than the generator.

**Comment by zsyzzsoft** [comment]
In my experiments with pix2pix and CycleGAN, I found that the Color DiffAugment may work but the performance gains are very limited. Probably the generator's architecture is too weak to overfit the discriminator.

**Comment by Kitty-sunray** [comment]
How about pix2pixHD? Spade/GauGAN?

**Comment by Kitty-sunray** [comment]
> 
> 
> In my experiments with pix2pix and CycleGAN, I found that the Color DiffAugment may work but the performance gains are very limited. Probably the generator's architecture is too weak to overfit the discriminator.
Would you please share pix2pix code so I can try to fit it into the pix2pixHD?

**Comment by zsyzzsoft** [comment]
@Kitty-sunray Haven't tried. Basically you can apply the diffaugment to every image (in pix2pix this is the concatenated image) before feeding into the discriminator.

**Comment by Kitty-sunray** [comment]
> 
> 
> @Kitty-sunray Haven't tried. Basically you can apply the diffaugment to every image (in pix2pix this is the concatenated image) before feeding into the discriminator.

augmentations should be exactly the same for each image in the concatenated pair, right? Also, there actually 2 pair of pairs been feed to D: first pair is "label->fake", second pair is "label=>real"; If augmentations for "label" and "fake" should be exactly the same, should they also be the same for "label->real" pair? I am currently only saving random to let the augmentations be the same within each pair, but not within pair of pairs. 
Thanks!
