### ISSUE TITLE
Some stylegan2 installation trouble

### ISSUE THREAD

**Issue by materialvision** [mit-han-lab/data-efficient-gans#14]
I had some errors running your stylegan2 code on Ubuntu 16, but found a solution here:
https://stackoverflow.com/questions/59342888/tensorflow-error-this-file-requires-compiler-and-library-support-for-the-iso-c#

Changed line 64 and 127 of dnnlib/tflib/custom_ops.py as in the stackoverflow answer and comment. Maybe something to change in this code, or note if anyone else have the same issue.

**Comment by zsyzzsoft** [comment]
I'm not sure why this is caused, since the original code works fine in my cases. Maybe I'll update the code if it turns out to be a general problem and has no side effects.
