### ISSUE TITLE
Question about IS and FID score reported.

### ISSUE THREAD

**Issue by MINGUKKANG** [mit-han-lab/data-efficient-gans#17]
Hi.

Thank you for your wondrous works, GANs with DiffAugment!

I wonder the evaluation details of your work: dataloader, IS, and FID values on imagenet 128 resolution experiments.

In the BigGAN paper and authors' PyTorch implementation, the authors wrote that cropping along with long edge and resizing images are used (plz refer to 453-476 lines of https://github.com/ajbrock/BigGAN-PyTorch/blob/master/utils.py).

Also, for evaluation:
1. they use 1,281,167  training images to calculate moments: mu, and covariance, for calculating FID.
2. they split 50,000 generated images into ten folds (each fold has 5,000 samples), and each fold is used to calculate IS.

However, your implementation of BigGAN on Imagenet:
1. use imagenet validation images (total 50,000) to calculate the moments for calculating FID (CRGAN, ICRGAN does).
2. use 50,000 generated images to calculate IS without splitting into 10 folds.
3. As can see at "data-efficient-gans/DiffAugment-biggan-imagenet/compare_gan/datasets.py" 476-491 lines, your implementation for pre-processing seems to use bounding box information (tf.image.sample_distorted_bounding_box). 

Since all values reported in your paper are calculated from your implementation, this is not a problem.
But, I just wonder about the details of your evaluation.

Thank you:)

Sincerely, 

MInguk Kang

**Comment by zsyzzsoft** [comment]
BigGAN-PyTorch is the unofficial implementation of BigGAN, and they have claimed that their FID calculation is not official. We believe that our FID calculation matches the most widely accepted version (the same as compare_gan), where the validation images are used and are only center cropped. The "distorted" version is only used for training.

**Comment by MINGUKKANG** [comment]
Thank you!

Your answer has really help me a lot.

In your paper, I think the comparison with other papers is fair.

I just want to summarize the evaluation protocol of recently published papers.

I would like to ask you a question that identifies the training and evaluation protocol used in your work.

[Training]
Use the "distorted" cropping method out of [distorted, random, middle, zoomed]  for the training dataset.

[Evaluation]
Use the center crop method for the validation (50K) dataset.

[FID]
Use 50k generated samples and 50K valuation images from the ILSVRC2012 dataset.

[IS]
Use 50K generated images that are contained in the single fold.

Is it correct that you learned and evaluated with the details above?

Thank you!

Sincerely, 

Minguk Kang

**Comment by zsyzzsoft** [comment]
Looks correct except that the "zoomed" cropping method is used for training in our configurations.
