### ISSUE TITLE
 How do you ensure that the results of two random operations are consistent？？

### ISSUE THREAD

**Issue by Johnson-yue** [mit-han-lab/data-efficient-gans#2]
https://github.com/mit-han-lab/data-efficient-gans/blob/ce3c9c4a710505ae3d7f9ee0410702903bfcf0a8/DiffAugment-stylegan2/training/loss.py#L19-L20

In your code ，you did twice DiffAugment 。 But torch.rand() in DiffAugment function, and the of value of it is not the same!!

I have the test in One Image and do DiffAugment twice, the result is different

**Comment by zsyzzsoft** [comment]
We only require the two random *functions* to be the same, i.e., having the same probability of mapping A to B. The two random outputs are not required to be the same.

**Comment by Johnson-yue** [comment]
Woo， this is point！！！ I got it
