### ISSUE TITLE
Generating images

### ISSUE THREAD

**Issue by Mshz2** [mit-han-lab/data-efficient-gans#22]
Hey there,

I once trained my custom dataset with 100 images with below configure (64 resolution)
```
!python3 run_100_shot.py --dataset=100-custom --resolution=64
```
and its sample at result dir is a concatenated image consists of 1024 small images. I could easily separate them and have 1000 images. That is good!
![fakes000300](https://user-images.githubusercontent.com/63469924/95146678-c2c69500-077e-11eb-8dde-d55f6022e5ca.png)

-The problem is when I make --resolution=256, it samples only a 120 small images at directory. Is there anyway that I could sample more images?!  like again 1024 images!

Thanks for your response

**Comment by zsyzzsoft** [comment]
You may set size='8k' at [this line](https://github.com/mit-han-lab/data-efficient-gans/blob/8da2c67d3d17cfd9261fefcd5815f8841ee05a3c/DiffAugment-stylegan2/run_100_shot.py#L32) to see more images, or add a custom size [here](https://github.com/mit-han-lab/data-efficient-gans/blob/8da2c67d3d17cfd9261fefcd5815f8841ee05a3c/DiffAugment-stylegan2/training/misc.py#L110). But note that this will significantly increase the size of the image file.

**Comment by Mshz2** [comment]
> You may set size='8k' at [this line](https://github.com/mit-han-lab/data-efficient-gans/blob/8da2c67d3d17cfd9261fefcd5815f8841ee05a3c/DiffAugment-stylegan2/run_100_shot.py#L32) to see more images, or add a custom size [here](https://github.com/mit-han-lab/data-efficient-gans/blob/8da2c67d3d17cfd9261fefcd5815f8841ee05a3c/DiffAugment-stylegan2/training/misc.py#L110). But note that this will significantly increase the size of the image file.

After I turned size = "8k", it gave 1024 images again for resolution=128 and 460 images for resolution=256. I tried to make size="16k" to get also 1024 images for resolution=256, but it did not work and only 1 image generated instead. May I ask if you have any idea, why?

**Comment by zsyzzsoft** [comment]
'16k' is not pre-defined. You may add a custom size in [this function](https://github.com/mit-han-lab/data-efficient-gans/blob/8da2c67d3d17cfd9261fefcd5815f8841ee05a3c/DiffAugment-stylegan2/training/misc.py#L110), e.g.,
`
    if size == '16k':
        gw = np.clip(15360 // training_set.shape[2], 7, 32)
        gh = np.clip(8640 // training_set.shape[1], 4, 32)
`

**Comment by datduong** [comment]
Hi, so if we set --resolution=256, then the code uses only images with resolution below 256 to train the model? Thanks.

**Comment by zsyzzsoft** [comment]
> Hi, so if we set --resolution=256, then the code uses only images with resolution below 256 to train the model? Thanks.

The code will resize all images to 256x256.
