### ISSUE TITLE
FID Score improvement

### ISSUE THREAD

**Issue by Mshz2** [mit-han-lab/data-efficient-gans#24]
Hi there,

I have a dataset of 600 images. I trained the styleGAN-1 with all of them (resolution = 256) and got the maximum FID = 86 at kimg = 7726.
For training  your data-efficient-gans network, I used 110 images (resolution = 256) and at kimg = 201, I got FID = 114, and at kimg = 301, the FID = 119. 
May I ask what should I do to get better FID score? because the tutorial says, the data-efficient network is supposed to get 1.7 time better FID than normal styleGAN. Thanks for your support and response.

Best

**Comment by zsyzzsoft** [comment]
The FID value is sensitive to the number of reference images. As the whole training set is used as the reference distribution, the FID values would be poorly comparable between different datasets (e.g., 110 vs. 600 in your case). I would suggest using the same datasets and training it a little longer.
