### ISSUE TITLE
training with grayscale images

### ISSUE THREAD

**Issue by Mshz2** [mit-han-lab/data-efficient-gans#26]
Hi there,

I wanted to train the network with grayscale images. To do so, after I cnvert my images to grayscale, I changed the num_channels=1 in training.networks_stylegan2. However, I still observe the same number of network parameters during training as when my images were rgb. May I ask you please why? or what did i do wrong?

Best Regards

**Comment by zsyzzsoft** [comment]
num_channels is automatically determined from the tfrecords dataset. Need to make sure that your `.tfrecords` file has 1 channel.
