### ISSUE TITLE
comparison with few shot gan

### ISSUE THREAD

**Issue by ak9250** [mit-han-lab/data-efficient-gans#27]
will there be an update to compare performance with few shot gan?
https://github.com/e-271/few-shot-gan

**Comment by zsyzzsoft** [comment]
Looks interesting, but its experiment does not seem to improve TransferGAN/FreezeD. Would be happy to hear about some comparison if anyone is interested.

**Comment by ak9250** [comment]
@zsyzzsoft seems to help for very small n, here n=5 for data efficients gans faces->sketches finetuning

<img width="964" alt="Screen Shot 2020-10-27 at 4 30 37 PM" src="https://user-images.githubusercontent.com/6818285/97358546-c62ad900-1871-11eb-8ec6-b608e88672ae.png">

**Comment by zsyzzsoft** [comment]
Fine-tuning methods are expected to help for very small n, since they use a large external dataset for pre-training.

**Comment by datduong** [comment]
@ak9250 Would you know what the result looks like when there are 100 images ? Thanks.
