### ISSUE TITLE
Training on TPU for StyleGan2

### ISSUE THREAD

**Issue by sarmientoj24** [mit-han-lab/data-efficient-gans#31]
Is it possible to use TPU from Google Colab to train using StyleGan2?

**Comment by zsyzzsoft** [comment]
It may be possible but currently we're not planning to implement it.

**Comment by gwern** [comment]
@sarmientoj24 If you want to train StyleGAN2 on TPUs, you can look into codebases that support it like shawwn's TPU fork: https://github.com/shawwn/stylegan2/tree/working This doesn't have ADA specifically. (Sid was working on them and got most of the way but I think ran into TPU problems.) If you really need ADA, doesn't Colab provide GPUs as well as TPUs? So you can run the original StyleGAN2-ADA code, I think.
