### ISSUE TITLE
Wrong illustration

### ISSUE THREAD

**Issue by woctezuma** [mit-han-lab/data-efficient-gans#33]
On [the project page](https://hanlab.mit.edu/projects/data-efficient-gans/), there is a wrong illustration for "LSUN-Cat Generation".

![project page](https://i.imgur.com/lr4DJLW.png)

Indeed, these two images are the same:

- https://hanlab.mit.edu/projects/data-efficient-gans/imgs/ffhq-horizontal.jpg
- https://hanlab.mit.edu/projects/data-efficient-gans/imgs/lsun-cat-horizontal.jpg

**Comment by zsyzzsoft** [comment]
Sorry, it's my mistake. Thanks for the correction!
