### ISSUE TITLE
Training seems to be stuck?

### ISSUE THREAD

**Issue by sarmientoj24** [mit-han-lab/data-efficient-gans#34]
I am currently training with with Colab using DiffAug StyleGan with this command

```
!python data-efficient-gans/DiffAugment-stylegan2/run_low_shot.py --dataset=images --num-gpus=1 \
  --DiffAugment=color,translation,cutout --resolution=256 \
  --total-kimg=100 --batch-size=8
```

Seems like the training is stuck? It has been an hour and the output is still this:
```
16x16/Conv1_down     2359808   (?, 512, 8, 8)      (3, 3, 512, 512)
16x16/Skip           262144    (?, 512, 8, 8)      (1, 1, 512, 512)
8x8/Conv0            2359808   (?, 512, 8, 8)      (3, 3, 512, 512)
8x8/Conv1_down       2359808   (?, 512, 4, 4)      (3, 3, 512, 512)
8x8/Skip             262144    (?, 512, 4, 4)      (1, 1, 512, 512)
4x4/MinibatchStddev  -         (?, 513, 4, 4)      -               
4x4/Conv             2364416   (?, 512, 4, 4)      (3, 3, 513, 512)
4x4/Dense0           4194816   (?, 512)            (8192, 512)     
Output               513       (?,)                (512, 1)        
scores_out           -         (?,)                -               
---                  ---       ---                 ---             
Total                28864129                                      

Building TensorFlow graph...
Initializing logs...
Training for 100 kimg...

tick 0     kimg 0.0      lod 0.00  minibatch 8    time 34s          sec/tick 33.8    sec/kimg 1055.01 maintenance 0.0    gpumem 8.8
Downloading http://d36zk2xti64re0.cloudfront.net/stylegan1/networks/metrics/inception_v3_features.pkl ... done
network-snapshot-000000        time 4m 11s       fid5k-train 414.4864
```

Or is this normal?

**Comment by shengyu-ponyai** [comment]
It usually takes like tens of minutes to see the next output. Maybe you were unluckily allocated a bad node.

**Comment by zsyzzsoft** [comment]
It usually takes like tens of minutes to see the next output. Maybe you were unluckily allocated a bad node.

**Comment by dodger** [comment]
> It usually takes like tens of minutes to see the next output. Maybe you were unluckily allocated a bad node.

He said had been stuck like that for an hour. That **_IS_** tens of minutes. Six tens of minutes, to be precise. I do not think you should have just closed this.

I'm having the same issue. With snapshot ticks set to 4, I should not be at over an hour running with only the init and fakes000000.jpg generated.

**Comment by Zeusward1939** [comment]
> > It usually takes like tens of minutes to see the next output. Maybe you were unluckily allocated a bad node.
> 
> He said had been stuck like that for an hour. That **_IS_** tens of minutes. Six tens of minutes, to be precise. I do not think you should have just closed this.
> 
> I'm having the same issue. With snapshot ticks set to 4, I should not be at over an hour running with only the init and fakes000000.jpg generated.

Hi, I got the same problem, the code stuck here. 
```
tick 0     kimg 0.0      time 1m 02s       sec/tick 3.7     sec/kimg 468.68  maintenance 57.9   cpumem 5.54   gpumem 11.90  augment 0.000
Evaluating metrics...
```
Have you solved this?
When I checked the CPU and GPU usage, I found that they were both close to 0%, but there was still some memory and VRAM usage like over 10GB.
