### ISSUE TITLE
how to change time to save chekpoint?

### ISSUE THREAD

**Issue by molo32** [mit-han-lab/data-efficient-gans#35]
how to change time to save chekpoint, eg every 30m 1hs?

**Comment by zsyzzsoft** [comment]
You may modify the image_snapshot_ticks and network_snapshot_ticks [here](https://github.com/mit-han-lab/data-efficient-gans/blob/0636848135afcfb56c331600f16b4e558580bcc9/DiffAugment-stylegan2/training/training_loop.py#L130) to e.g. 1.

**Comment by molo32** [comment]
great, do you have any idea how to reduce the time between each trick?

**Comment by zsyzzsoft** [comment]
There is a map from the resolution to the number of iterations (in terms of kimg) of each tick [here](https://github.com/mit-han-lab/data-efficient-gans/blob/0636848135afcfb56c331600f16b4e558580bcc9/DiffAugment-stylegan2/training/training_loop.py#L65)..
