### ISSUE TITLE
OOM when allocating tensor with shape[4,32,1024,1024] where is the 32 coming from?

### ISSUE THREAD

**Issue by dtkatch** [mit-han-lab/data-efficient-gans#38]
So I have access to a V100 on which I successfully trained on a dataset of 512x512 images. However, when I moved up to 1024x1024 I had to reduce the batch size to 2 in order to avoid OOM errors. This resulted in monochromatic looking images. I'm wondering where the 32 in:

  (0) Resource exhausted: OOM when allocating tensor with shape[4,32,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

is coming from and if it can be reduced to 16 so that the batch size can be 4 which will hopefully result in colorful images.

Thank you for your help!

**Comment by zsyzzsoft** [comment]
32 is the number of channels, determined from "fmap-base" and "fmap-max". E.g., you can reduce --fmap-base from the default 16384 to 8192 so that the 32 would become 16.
