### ISSUE TITLE
kimg meaning

### ISSUE THREAD

**Issue by molo32** [mit-han-lab/data-efficient-gans#39]
what does kimg mean?
when I summarize a pkl the kimg starts from 0.
Does it affect something from where kimg starts training?

**Comment by zsyzzsoft** [comment]
kimg means the training progress in terms of one thousand of images. resume-kimg specifies where to start training.

**Comment by molo32** [comment]
I have a question, if before saving the pkl I was in kimg 80, when resuming training should I put --resume-kim 80?
what if i leave it at 0?

**Comment by zsyzzsoft** [comment]
No problem to leave it at 0 if you still want the training length to be `total-kimg`. If you set the `resume-kimg` properly, then the remaining training length would be `total-kimg` - `resume-kimg`.
