### ISSUE TITLE
code question in rand_cutout 

### ISSUE THREAD

**Issue by foobar8675** [mit-han-lab/data-efficient-gans#40]
in this method `rand_cutout` i'm not able to follow what this line is doing

https://github.com/mit-han-lab/data-efficient-gans/blob/96d6d871bf47d8dd3d280b77a5c3a01c674a7acd/DiffAugment-biggan-cifar/DiffAugment_pytorch.py#L67

is it just indexing into the mask? `grid_batch` and `grid_x` and `grid_y` also have multiple dimensions, so it's throwing me off a bit. 

any help to clarify would be much appreciated.

**Comment by zsyzzsoft** [comment]
Yes, it's equivalent to `for i, j, k: mask[grid_batch[i, j, k], grid_x[i, j, k], grid_y[i, j, k]] = 0`

**Comment by foobar8675** [comment]
ah ic. i learned something new. thank you!
