### ISSUE TITLE
 raise RuntimeError('No GPU devices found')

### ISSUE THREAD

**Issue by jinzhenmu** [mit-han-lab/data-efficient-gans#41]
-   DiffAugment-stylegan2/dnnlib/tflib/custom_ops.py", line 52, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')

- RuntimeError: No GPU devices found

- The GPU in my PC is 3   RTX 2080Ti

- what happens?

**Comment by jinzhenmu** [comment]
- nvcc: NVIDIA (R) Cuda compiler driver

Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

-

**Comment by jinzhenmu** [comment]
- I change the custom_ops.py, line 50 as:

 

- gpus = [x for x in device_lib.list_local_devices() if x.device_type == 'XLA_GPU']

- and then i got :

- custom_ops.py", line 45, in _get_compute_cap
    major = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by zsyzzsoft** [comment]
Does your tensorflow has GPU support? Please try uninstall `tensorflow` and then install `tensorflow-gpu`

**Comment by jinzhenmu** [comment]
- not use the " pip install tensorflow-gpu==1.15"

- use the conda install ensorflow-gpu==1.15
