### ISSUE TITLE
DiffAug with other GAN architecture

### ISSUE THREAD

**Issue by Ch4nYH** [mit-han-lab/data-efficient-gans#42]
Thank you for your wonderful job! I was wondering did you try diffaug on other GAN networks like SNGAN? Thank you in advance!

**Comment by zsyzzsoft** [comment]
We have not tried other earlier GAN architectures, but I think that BigGAN is an improved version of SNGAN so one may get similar improvements.

**Comment by Ch4nYH** [comment]
Thank you!
