### ISSUE TITLE
AssertionError when training my own dataset

### ISSUE THREAD

**Issue by Brand4** [mit-han-lab/data-efficient-gans#43]
When trying to train the model with a custom dataset, after specifying the path to the dataset in "run_slow_shot.py" with the argument "dataset". I get an error, AssertionError : in create_dataset assert os.path.isdir(data_dir).though I specified the right folder path. 
What is the right folder path? Thank you！
(my conmmand is python run_slow_shot.py --dataset=''z:\GraduateWork\data-efficient-gans-master\DiffAugment-stylegan2\datasets\opera'')
### Error Report
Traceback (most recent call last):
  File "z:/GraduateWork/data-efficient-gans-master/DiffAugment-stylegan2/run_low_shot.py", line 171, in <module>
    main()
  File "z:/GraduateWork/data-efficient-gans-master/DiffAugment-stylegan2/run_low_shot.py", line 165, in main
    run(**vars(args))
  File "z:/GraduateWork/data-efficient-gans-master/DiffAugment-stylegan2/run_low_shot.py", line 37, in run
    dataset = dataset_tool.create_dataset(dataset, resolution)
  File "z:\GraduateWork\data-efficient-gans-master\DiffAugment-stylegan2\training\dataset_tool.py", line 194, in create_dataset
    assert os.path.isdir(data_dir)
AssertionError
```

**Comment by zsyzzsoft** [comment]
I'm not sure what is the problem but could you try replacing "\" with "/"?

**Comment by Brand4** [comment]
> I'm not sure what is the problem but could you try replacing `\` with `/`?

I have tried both '/' and '\', but it still has this problem...

**Comment by zsyzzsoft** [comment]
That's weird... Have you tried the relative path?

**Comment by Brand4** [comment]
> That's weird... Have you tried the relative path?

Yes, I tried the relative path. It also has this problem.

**Comment by Brand4** [comment]
if I assert this path z:\GraduateWork\data-efficient-gans-master\DiffAugment-stylegan2\datasets, it is true. 
But if I assert this path z:\GraduateWork\data-efficient-gans-master\DiffAugment-stylegan2\datasets\opera, it is false.(but opera folder does exist)

**Comment by eliohead** [comment]
> if I assert this path z:\GraduateWork\data-efficient-gans-master\DiffAugment-stylegan2\datasets, it is true.
> But if I assert this path z:\GraduateWork\data-efficient-gans-master\DiffAugment-stylegan2\datasets\opera, it is false.(but opera folder does exist)

It is probably set to run on 'datasets' folder. So you have to delete that 'opera' folder and write this:
'z:/GraduateWork/data-efficient-gans-master/DiffAugment-stylegan2/datasets'
