### ISSUE TITLE
Error when train on Colab

### ISSUE THREAD

**Issue by eliohead** [mit-han-lab/data-efficient-gans#44]
It says me 'ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 2.1.0;' when try to train on the Colab notebook.
But after upgrading I got this other error: 'no module named tensorflow.contrib'.

**Comment by zsyzzsoft** [comment]
Hi, please `pip install tensorflow-gpu==1.15.0` and `pip install tensorflow-datasets==2.1.0`. I have updated the Colab code accordingly.

**Comment by eliohead** [comment]
Thanks. It works.
