### ISSUE TITLE
No such file or directory: inception_moments.pkl

### ISSUE THREAD

**Issue by datduong** [mit-han-lab/data-efficient-gans#49]
Hi, I am running the differentiable data aug. with biggan model. I get this error 

`  File "/vf/users/duongdb/data-efficient-gans/DiffAugment-biggan-cifar/dnnlib/util.py", line 422, in open_file_or_url
    return open(file_or_url, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'SomeDataSetName_inception_moments.pkl'`

where the `SomeDataSetName` is my own dataset. Do I need to run the file `calculate_inception_moments.py` in ajbrock's biggan github? 

Thanks.

**Comment by zsyzzsoft** [comment]
The code should be able to compute the inception moments automatically, see [these lines](https://github.com/mit-han-lab/data-efficient-gans/blob/f99c96072379c0fd84e52634cefbdb8e6b14753a/DiffAugment-biggan-cifar/inception_tf.py#L33-L50)

**Comment by datduong** [comment]
Thank you.
