### ISSUE TITLE
Do you have a sample Colab example with pytorch or tensorflow?

### ISSUE THREAD

**Issue by shyamalschandra** [mit-han-lab/data-efficient-gans#5]
Do you have a sample Colab example with pytorch or tensorflow?  That would be great!

**Comment by zsyzzsoft** [comment]
Maybe I will work on that!

**Comment by zsyzzsoft** [comment]
Our [colab tutorial](https://colab.research.google.com/gist/zsyzzsoft/5fbb71b9bf9a3217576bebae5de46fc2/data-efficient-gans.ipynb) is released!

**Comment by shyamalschandra** [comment]
I haven't tested it but thank you for your help!
