### ISSUE TITLE
Replicating FFHQ architecture

### ISSUE THREAD

**Issue by slala2121** [mit-han-lab/data-efficient-gans#50]
The paper mentions that the "# feature maps at shallow layers is halved to match the architecture of ADA". I was skimming over the code but couldn't find where this was implemented. Thanks.

**Comment by zsyzzsoft** [comment]
Hi, sorry for the delay. This is implemented as an `fmap-base` argument [here](https://github.com/mit-han-lab/data-efficient-gans/blob/f99c96072379c0fd84e52634cefbdb8e6b14753a/DiffAugment-stylegan2/run_ffhq.py#L144), and the number of feature maps at each level is determined [here](https://github.com/mit-han-lab/data-efficient-gans/blob/f99c96072379c0fd84e52634cefbdb8e6b14753a/DiffAugment-stylegan2/training/networks_stylegan2.py#L339).

**Comment by slala2121** [comment]
Thanks
