### ISSUE TITLE
About cutout implementation

### ISSUE THREAD

**Issue by yueruchen** [mit-han-lab/data-efficient-gans#53]
Hi,

Thanks for sharing this work. I have a question about the `cutout` implementation on PyTorch. My understanding is that we just need to mask an area of image. So why not just set those area to 0 value. Like
```
x[:, :, h:h+offset, w:w+offset] = 0
return x
```
I feel like this is the same as `x * mask`?

**Comment by zsyzzsoft** [comment]
`h` and `w` in your code can vary across the batch dimension. Does pytorch support this?

**Comment by yueruchen** [comment]
Thanks, I got it.
