### ISSUE TITLE
BigGAN: why only use translation?

### ISSUE THREAD

**Issue by AlexiaJM** [mit-han-lab/data-efficient-gans#59]
It's not clear from the paper why only translation is used on BigGAN. Have color and cutout been tried? Do they not improve results or do they make them worse?

Alexia

**Comment by AlexiaJM** [comment]
One the same vein, was CR tried on ImageNet?

**Comment by zsyzzsoft** [comment]
Color and Cutout make the ImageNet results worse. However, I found that they may improve the results when EMA (exponential moving average of generator's weights) is not used. I think maybe ImageNet experiments need more careful tuning to make things work.

**Comment by AlexiaJM** [comment]
Thanks, I'll have to experiment a little bit then.
