### ISSUE TITLE
Testing samples for calculating FID on 100-shot tasks.

### ISSUE THREAD

**Issue by Puneet2000** [mit-han-lab/data-efficient-gans#6]
Hi,
Can you please share the testing samples (5k) used to calculate the FID on few-shot generation (AnimalFaces:  cat and dog)? The Animal Faces dataset contains only 160 examples of cat and 389 examples of dog.
Thanks

**Comment by zsyzzsoft** [comment]
We sample 5k generated samples and the whole training set is the reference distribution. There are no separate testing samples.

**Comment by Puneet2000** [comment]
@zsyzzsoft Thanks a lot for clarifying.
