### ISSUE TITLE
fmap-base and fmap-max meaning

### ISSUE THREAD

**Issue by iumyx2612** [mit-han-lab/data-efficient-gans#69]
I see "fmap-base" in run_low_shot.py is "Number of feature maps" but in networks_stylegan2.py is "Overall multiplier for the number of feature maps". 
Same for "fmap-max", in run_low_shot.py is "Maximum number of feature maps", in networks_stylegan2.py is "Maximum number of feature maps in any layer". I assume fmap-max has the same meaning
Can you explain "fmap-base" clearly?

**Comment by zsyzzsoft** [comment]
`fmap-base` is the overall multiplier for the number of feature maps. You can have a look at [this line of code](https://github.com/mit-han-lab/data-efficient-gans/blob/3a5ba9f66fe258a04ce8be3b358b44e23941a290/DiffAugment-stylegan2/training/networks_stylegan2.py#L339), which is the formula of determining the number of feature maps at each layer depending on `fmap-base` and `fmap-max`.

**Comment by iumyx2612** [comment]
Oh, I got it, thank you
