### ISSUE TITLE
Model collapse problems

### ISSUE THREAD

**Issue by RayGuo-C** [mit-han-lab/data-efficient-gans#76]
Dear, 

I have trained the stylegan2 + DiffAugment (DiffAugment-stylegan2-pytorch) with a simple model (64*64pixel), like following. 
![1628431987](https://user-images.githubusercontent.com/34149368/128635045-2efbecc3-e270-420a-8e2a-bf1ecff44af6.png)

But the model collapse occurred. Like following, 
![1628431987](https://user-images.githubusercontent.com/34149368/128635253-e17d0ed7-2325-4ec6-adc7-4732a34041ea.jpg)

I think the main reason is that the network is too strong(Filters in conv2D keep same). But there are no parameters to adjust that. As I want to generated high quantity images with limited data, the wgan-gp cannot produce attractive results although with DiffAugment. So can you give me some suggestions on this?
![image](https://user-images.githubusercontent.com/34149368/128635412-a4800049-28a9-4506-9f76-85c3618b189a.png)

**Comment by zsyzzsoft** [comment]
You can try adjusting 'fmap-base', which is an overall multiplier of the number of channels.

**Comment by RayGuo-C** [comment]
Oh. Thank you. I just saw the pytorch version. Now it works. But the results are not ideal. There should not have artifacts. But it has. Do you have some suggestions on that?
![图片](https://user-images.githubusercontent.com/34149368/128644950-41eeeb09-d375-4f4e-91e2-64acc6ee15e1.png)

**Comment by RayGuo-C** [comment]
Thank you.
