### ISSUE TITLE
TPU support 

### ISSUE THREAD

**Issue by rmermin** [mit-han-lab/data-efficient-gans#8]
Hi, are you planning to add TPU support only for DiffAugment-biggan-imagenet and only on the Pytorch backend?

**Comment by zsyzzsoft** [comment]
DiffAugment-biggan-imagenet will be based on the [compare_gan](https://github.com/google/compare_gan) codebase, which is in TensorFlow and mainly designed for TPU.

**Comment by rmermin** [comment]
Are you planning to do the same for DiffAugment-stylegan2?

**Comment by zsyzzsoft** [comment]
I'm also expecting a TPU version of StyleGAN2, but I'm currently not planning to do that.
