### ISSUE TITLE
How to train DiffAugment-biggan with the self-made dataset?

### ISSUE THREAD

**Issue by Charlie-Wilson0211** [mit-han-lab/data-efficient-gans#90]
If I want to train the few-shot dataset of 256*256 pixel resolution and less than 100 samples, and  how to train DiffAugment-biggan with the few-shot dataset?

**Comment by zsyzzsoft** [comment]
This is not recommended as BigGAN does not perform as well as StyleGANs with very limited data. However, if you want to try out, you may refer to the original repo's [README](https://github.com/ajbrock/BigGAN-PyTorch#fine-tuning-using-your-own-dataset-or-making-new-training-functions).

**Comment by Charlie-Wilson0211** [comment]
Thanks for your help

**Comment by arslanjavedghouri** [comment]
@zsyzzsoft as you mentioned the link but in that code, there is no Differentiable Augmentation implemented to get good results with the limited dataset.
